name: minions-applications-blog
project_scope: child
child_type: blog
parent_project: minions-applications-workspace
description: Standard compliance definition for minions-applications-blog
priority: high
deploy_url: null
tags: null
category: minion-toolbox
